// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD04cd4kvZz1qdTsoV2Hz1m0pa67oc6Zew',
    appId: '1:199224331826:web:4970389453452d7625762b',
    messagingSenderId: '199224331826',
    projectId: 'mahasiswa-f5627',
    authDomain: 'mahasiswa-f5627.firebaseapp.com',
    databaseURL: 'https://mahasiswa-f5627-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mahasiswa-f5627.firebasestorage.app',
    measurementId: 'G-WKQ8WLHNCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFCrA2nOPYG0UqIheuHKvfDGFN36GAmBk',
    appId: '1:199224331826:android:4af1fbbe1ae290c525762b',
    messagingSenderId: '199224331826',
    projectId: 'mahasiswa-f5627',
    databaseURL: 'https://mahasiswa-f5627-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mahasiswa-f5627.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD04cd4kvZz1qdTsoV2Hz1m0pa67oc6Zew',
    appId: '1:199224331826:web:60327c1075826fed25762b',
    messagingSenderId: '199224331826',
    projectId: 'mahasiswa-f5627',
    authDomain: 'mahasiswa-f5627.firebaseapp.com',
    databaseURL: 'https://mahasiswa-f5627-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mahasiswa-f5627.firebasestorage.app',
    measurementId: 'G-NERTZJQEC0',
  );

}